project_id = "kqaullpjkeiopgfhqans"

[functions.send-contact-notification]
verify_jwt = false

[functions.send-cofounder-invite]
verify_jwt = false

[functions.send-enterprise-notification]
verify_jwt = false

[functions.send-compliance-notification]
verify_jwt = false

[functions.send-crm-notification]
verify_jwt = false

[functions.send-voice-notification]
verify_jwt = false
